# Generated by Django 5.2.2 on 2025-07-14 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_storemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanager',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.store'),
        ),
    ]
